print("привет мир!")
print("hello world!")
print("hola mundo!")
print("Γεια σου κόσμο!")
print("дорообо дойду!")
print("hallo Welt!")
print("здраво светот!")
print("こんにちは世界!")
print("habari dunia!")
print("Сайн байна уу Дэлхийн!")